name: faded_scrollable
description: "A wrapper for any scrollable widget that will add fade in/out effect on top & bottom respectively whenever there is scrollable content beyond the screen's extent."
version: 1.0.0
repository: https://github.com/notarirob/faded_scrollable

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
